apiVersion: v1
kind: Secret
metadata:
  name: obsidian-backup-secrets
  namespace: obsidian-backup
type: Opaque
stringData:
  OBSIDIAN_AUTH_TOKEN: "your-auth-token-here"
  E2EE_PASSWORD: "your-e2ee-password-here"
  git-ssh-key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...your deploy key...
    -----END OPENSSH PRIVATE KEY-----
